const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

async function main() {
  const allWeeks = await prisma.trainingWeek.createMany({
    data: {
      weekNumber: 1,
      weekStart: 'December 20',
      weekEnd: 'December 26',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 2,
      weekStart: 'December 27',
      weekEnd: 'January 2',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 3,
      weekStart: 'January 3',
      weekEnd: 'January 9',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 4,
      weekStart: 'January 10',
      weekEnd: 'January 16',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 5,
      weekStart: 'January 17',
      weekEnd: 'January 23',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 6,
      weekStart: 'January 24',
      weekEnd: 'January 30',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 7,
      weekStart: 'January 31',
      weekEnd: 'February 6',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 8,
      weekStart: 'February 7',
      weekEnd: 'February 13',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 9,
      weekStart: 'February 14',
      weekEnd: 'February 20',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 10,
      weekStart: 'February 21',
      weekEnd: 'February 27',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 11,
      weekStart: 'February 28',
      weekEnd: 'March 6',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 12,
      weekStart: 'March 7',
      weekEnd: 'March 13',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 13,
      weekStart: 'March 14',
      weekEnd: 'March 20',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 14,
      weekStart: 'March 21',
      weekEnd: 'March 27',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 15,
      weekStart: 'March 28',
      weekEnd: 'April 3',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 16,
      weekStart: 'April 4',
      weekEnd: 'April 10',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 17,
      weekStart: 'April 11',
      weekEnd: 'April 17',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
      weekNumber: 18,
      weekStart: 'April 18',
      weekEnd: 'April 24',
      trainingDay: [
        'Monday',
        'Tuesday',
        'Wednesday',
        'Thursday',
        'Friday',
        'Saturday',
        'Sunday',
      ],
    },
  });
  const allUsers = await prisma.user.createMany({
    data: [
      {
        name: 'Jessica',
        email: 'jessicalyngallagher@me.com',
      },
      {
        name: 'Stephen',
        email: 'stephengallaghercpa@gmail.com'
      },
    ]
  });
  const allTrainingPlans = await prisma.trainingPlan.createMany({
    data: [
      
    ]
  })
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
